---
title: "Programación sesiones"
slug: programacion
---

<embed src="../programa/cuanti2019prog_sesiones2.pdf" type="application/pdf" width="90%" height="600px" />

[(programación original)](../programa/cuanti2019prog_sesiones.pdf)

<div style="width:130%">

<i class="fas fa-chalkboard-teacher"></i> Documentos de presentación

<i class="fas fa-book-reader"></i> Lecturas

<i class="fas fa-user-edit"></i> Evaluaciones, talleres y otros


<br>

<div class="wrap-collabsible">
<input id="collapsible1" class="toggle" type="checkbox"><label for="collapsible1" class="lbl-toggle">
Unidad 1: Características de la investigación cuantitativa
</label>
<div class="collapsible-content">
<div class="content-inner">
<div style="width:180%">

| | | <i class="fas fa-chalkboard-teacher"></i> |<i class="fas fa-book-reader"></i> | <i class="fas fa-user-edit"></i> |
|----- | -- |-----------------|-------------------------- |-------------|
| Agosto | 8  | [**Introducción**](../docpres/01_intro/01_intro.html)   | [- Hernández et al. Cap 3: Planteamiento cuantitativo del problema](../readings/cap3Hernandezetal2014.pdf)  | |
| Septiembre   | 26 | [Formulación de una investigación cuantitativa](../docpres/02_formu/02_formu.html)     |    [- Hernández et al. Cap 5: Definición del alcance de la inv.](../readings/cap5Hernandezetal2014.pdf)  | |
|  |   |  | [- Gayo et al 2019 Elección escolar](../readings/gayo_etal2019eleccionescolar.pdf)  |   |
|  |   |     |    [- Hernández et al. Cap 7: Diseño de investigación](../readings/cap7Hernandezetal2014.pdf)  |  |
|   |   |   | [- Espinoza & Nuñez 2014 movilidad ocupacional en Chile](../readings/Espinoza&Nunez2014movilidadchile.pdf)  | Inscripción de grupos para trabajos  |
|   |   | Ética en la investigación social  |  [- Hall 2017 ética en la investigación social](../readings/hall2017eticainvsocial.pdf)) ]  |   |
|   |   | Ciencia Abierta     | [Fressoli & Arza 2018 los desafíos de las prácticas de ciencia abierta](../readings/fressoli&arza2018desafioscienciaabierta.pdf)  |   |

</div>
</div>
</div>

<br>

<div class="wrap-collabsible">
<input id="collapsible2" class="toggle" type="checkbox"><label for="collapsible2" class="lbl-toggle">
Unidad 2: Medición y operacionalización
</label>
<div class="collapsible-content">
<div class="content-inner">
<div style="width:180%">

| | | <i class="fas fa-chalkboard-teacher"></i> |<i class="fas fa-book-reader"></i> | <i class="fas fa-user-edit"></i> |
|----- | -- |-----------------|-------------------------- |-------------|
| Octubre | 3  | [Operacionalización, confiablidad y validez]() | [Blanco 2011 Cap 1](../readings/BlancoCap1.pdf) | Panel con invitad_s   |
|   |   |   | [Babbie cap 6 Operacionalización](../readings/BabbieCap6.pdf)  |   |
|   |   |   | [Latiesa Validez y confiabilidad](../readings/Latiesa2010ValidezConfiabilidad.pdf) |   |
|   |   |   | [Hernández cap 9 Recolección de datos](../readings/cap9Hernandezetal2014.pdf)  |   |
|   |     |    |   |   |
|   | 10  | [Diseño de cuestionarios y preguntas ]() | [Clark-Carter et al Cap 6: Medición de actitudes y significados]()  | [Informe 1 Análisis artículo (20%)](../evaluaciones#inf1) |
|   | 17  |   | [Asún, R. (2006). Construcción de cuestionarios y escalas]()  |Taller: Diseño de cuestionarios en formato web |
|   |     |   | [Corbetta cap 6 la técnica de las escalas]()  |  |
|   | 24  | [Construcción de indicadores ]()  | [Babbie cap 7 Indices y escalas]()  |   |
|   | 31  |   |  | [Informe 2 Diseño (30%)](../evaluaciones#inf2)  |

</div>
</div>
</div>

<br>

<div class="wrap-collabsible">
<input id="collapsible3" class="toggle" type="checkbox"><label for="collapsible3" class="lbl-toggle">
Unidad 3: Implementación y reporte
</label>
<div class="collapsible-content">
<div class="content-inner">
<div style="width:180%">

| | | <i class="fas fa-chalkboard-teacher"></i> |<i class="fas fa-book-reader"></i> | <i class="fas fa-user-edit"></i> |
|----- | -- |-----------------|-------------------------- |-------------|
| Noviembre | 7  | [Inverstigación por encuestas sociales]() | [Corbetta cap 5 La encuesta por muestreo]() | |
|   |   |   | [Clark-Carter et al Cap 5: Entrevistas y encuestas]() |   |
|           | 14 | [Reporte y comunicación de resultados I]() | [Clark-Carter et al Cap 6: Medición de actitudes y significados]()  | [Informe 3 Pares 10%](../evaluaciones#inf3) |
|           | 21 | [Reporte y comunicación de resultados  II]()  | [Clark-Carter et al Cap 23: Cómo presentar la investigación]()  |  |
|            | 28 |  |  | [Informe 4: Final (40%)](../evaluaciones#inf4) |
|   |   |   |   | [Entrega Autoevaluación](../evaluaciones#inf5)  |

</div>
</div>
</div>

</div>
