---
title: "Trabajos y Prácticas"
output:
  blogdown::html_page:
    toc: true
---


# Grupos de trabajo (actualizado 3 Oct. 2019)

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRZrZ6_lXX7o5p-zRjES6eJBd-9pdAUW5XxZQKKjTuMhmmrkk481DJYS4mgoTdZOHJhW-QvRTTdYp-I/pubhtml?widget=true&amp;headers=false" width="1000" height="1000"></iframe>


# Temas de trabajo actualizados (Diciembre 2019)

## Grupo 1

**Catalina Dupuy, Antonia Cornejo, Nathalie Bustamante**

Definición violencia político sexual:
Según CIDH, la violencia sexual implica la realización de acciones de naturaleza sexual que se cometen contra una persona sin su consentimiento, que comprenden la invasión física del cuerpo humano y otros actos que incluso no involucran contacto físico alguno. Desde la dictadura cívico- militar, en los años 80 ocurrido en nuestro país, la violencia sexual ha sido manipulada politicamente para el control de personas, principalmente mujeres, que se han encontrado en resistencia a la opresión impuesta por el estado; este mecanismo de violencia es legitimada por parte del gobierno para la mantención del orden impuesto.

Hipótesis: El estallido social que se produjo en octubre de este año ha significado un cuestionamiento de la cualidad * democrática inmersa en nuestro país debido a la utilización de recursos que atentan al pleno desenvolvimiento de los derechos humanos de las personas que viven en Chile. La violencia político sexual es uno de estos recursos, que además de atentar en contra de estos principios que garantizan una democracia, responde a la lógica del poder patriarcal en el que las mujeres son las principales afectadas.

## Grupo 2

**Danae Pedraza, Valentina Yañez, Catalina Roa y yo, Emilia Cuadros.**

Nuestro tema de estudio es la percepción de las personas hacia distintos tipos de violencias, y por lo tanto crímenes, ya sea cuando son efectuados por parte del Estado o de la misma población. En este sentido, nuestro objeto de estudio es la población residente en Santiago de Chile, mayores de 18 años, de todos los estratos socioeconómicos y sexos, en el contexto de la contingencia política social actual. Las preguntas estarán orientadas en tres dimensiones principales: (1) validar a priori el crimen y la violencia ejercida, (2) ponerse en la posición de hacer el crimen en sí y (3) experiencia directa de haber participado o sufrido en/de algún crimen. Nuestras hipótesis son (1) el darle más importancia a crímenes de lesa humanidad que a crímenes que atentan contra la propiedad privada y/o pública, depende del estatus social de esa persona; (2) personas de estatus socioeconómico más alto tenderán a realzar la idea de la destrucción pública y/o privada por sobre crímenes de lesa humanidad, legitimando la necesidad de un cierto orden; y (3) personas de estatus socioeconómico más bajo tenderán a participar más de estos crímenes generalmente repudiados por clases más altas y así, siendo más afectados por crímenes de lesa humanidad.

## Grupo 3

**Vicente Otto, Martín Henríquez, Macarena Rodriguez, Ignacio Nuñez**

Como grupo buscamos enfocar nuestra investigación al tema del consumo y el comercio de drogas en el contexto del estallido social. Nuestro objeto de estudio radicaría en los cambios en los niveles de consumo y en las razones que justifican el mismo desde distintos actores. De esta forma, buscamos percepciones dentro del contexto de la movilización en torno a cómo se inserta o se perpetua el consumo de alcohol, marihuana, y otras sustancias en la configuración del espacio de protesta, a la vez de comprender como este puede aportar o desacreditar a la movilización y/o a los distintos actores (incluyendo a carabineros) en el marco de la opinión publica.

A modo de justificación del estudio, creemos que es pertinente dado el contexto de segregación históricamente perpetuada (económica y su manifestación espacial) y polarización política, lo que configura actores en polos opuestos de opinión sobre todo desde el lugar donde se habla, lo que se manifestaría también en la configuración de los espacios de protesta y que fenómenos son o no legitimados.

Nuestra hipótesis es que encontraremos polos opuestos de opinión respecto a la valoración dada al consumo de alcohol y drogas tomando en cuenta la posición política tomada sobre la movilización social como también si se ha participado o no en ella. A su vez, y por el lado de los niveles de consumo, encontraremos un incremento y/o nuevas significaciones dadas al fenómeno, en su mayoría atribuido al contexto actual y como ha operado en la cotidianidad de lxs actores.


## Grupo 4

**Génesis Báez, Pablo Campos, Sofia Fraile, Sofia Lovazzano.**

Se propuso entre el profesor y compañeres mantener la temática de proyecciones de vida y, en vez vincularlo con la crisis climática, estudiar si éstas han cambiado con el estallido social de octubre. El profesor sugirió estudiarlo en términos de optimismo/pesimismo, incertidumbre y/o estatus subjetivo.

Tema de estudio: El tema de interés corresponde a estudiar en qué medida el estallido social ha modificado las proyecciones de vida de las personas en términos optimistas o pesimistas según su estatus social subjetivo e identificación política. Pregunta de investigación: ¿En qué medida en Chile el estallido social de octubre ha modificado las proyecciones de vida de las personas, en cuanto a optimismo y/o pesimismo, según su estatus social subjetivo e identificación política? Objetivo general: Describir el cambio generado durante el estallido social de octubre del 2019 ocurrido en Chile, en las proyecciones de vida de las personas en cuanto a optimismo y/o pesimismo según su estatus social subjetivo e identificación política.

_Objetivos específicos_

- Describir las proyecciones de vida de las personas en cuanto a optimismo y/o
pesimismo.
- Identificar el estatus social subjetivo e identificación política de las personas.
- Relacionar las proyecciones de vida de las personas en cuanto a optimismo y/o
pesimismo con el estatus social subjetivo e identificación política.
Hipótesis: pendiente.

--
## Grupo 5

**Valentina Andreani, Bárbara Danús, Agatha Castro y Fabiana Ivankovic.**

Nuestra temática de interés tiene que ver con las percepciones de la gente (según género y edad) sobre la consigna “No + abusos” y si esta consigna la gente la relaciona sólo con aspectos materiales, ya sean salarios, pensiones,etc., o si incluyen dentro de ésta las demandas feministas (relacionadas con violencia, por ejemplo). El objeto de estudio estaría más centrado en el concepto de “abuso” y si la gente incluye las demandas feministas dentro del concepto global, más que en las prioridades que le asigna la gente a las demandas feministas.


## Grupo 6

**Blas Duhalde, Lucas Martín, Lucas Valderrama**

La siguiente investigación busca tratar con los temas de confianza en las instituciones y apoyo a las manifestaciones sociales que han venido ocurriendo desde el pasado 18 de octubre. Al mencionar instituciones nos referimos a organizaciones que reúnen a un grupo de personas para cumplir con una función específica y crucial para el funcionamiento de la sociedad (postulado por los estructural-funcionalistas como Parsons), y que cuentan con normas reglamentadas y roles que permiten la longevidad de las instituciones a través del tiempo. Para los objetivos de este trabajo evaluaremos una cantidad limitada pero relevante de instituciones, que han tenido un papel mayor o menor en la trayectoria de las manifestaciones sociales. Por otro lado, nos gustaría entender el concepto de confianza desde una perspectiva estrictamente sociológica. En este sentido, nos gustaría tomar en parte la definición que Luhmann ocupa en su libro Confianza y Poder (1979): la confianza es un elemento principal para el mantenimiento del orden social, debido a que los agentes no conocen ni entienden el actuar de todas las instituciones de la sociedad, tienen que confiar en que éstas actuarán según lo que estas mismas presumen cumplir. La hipótesis es lógica: a menor confianza en las instituciones, y por ende en el orden establecido, mayor apoyo al movimiento social, y viceversa. Por último, cabe destacar que, si bien trataremos de diferenciar los tipos de apoyo que se les dará a las manifestaciones sociales, no lo consideramos crucial para entender el efecto de la confianza (o de la falta de ella) en los movimientos sociales.

## Grupo 9

**Francisco Adasme, Melissa Alava, Marcelo Nogués, Catalina Tropa.**

En el marco del estallido social iniciado a mediados de Octubre de este año, nos parece interesante indagar sobre uno los rasgos más destacados que ha aflorado en el contexto de las recientes movilizaciones, este es la organización autoconvocada por parte de diferentes grupos sociales. En particular, nos interesa medir como ha aumentado la participación de las personas en organizaciones autoconvocadas surgidas desde el estallido social, tomando como variables a analizar el rango etario y su participación en mencionadas instancias. Esta medición nos mostrará un pincelado de la crisis social y politica por la que atraviesa el país, en vista de la necesidad de organización en espacios no tradicionales. Así, planteamos que, presentando nuestra hipótesis inicial, los resultados de la medición arrojarán una relación positiva en la participación en organizaciones autoconvocadas dentro de grupos etarios juveniles. Por el contrario anticipamos encontrar una relación negativa entre la participación en espacios autoconvocados y rangos etarios más longevos.

Este adelanto de las observaciones surge desde las experiencias que lxs integrantes del grupo tienen del proceso social que atraviesa el país, puesto que, desde nuestra perspectiva, en estas organizaciones autoconvocadas se concentra mayormente una población de carácter “joven/adulto joven”, quienes buscan una forma de organizarse políticamente y con miras a la orgánica horizontal que plantean estas organizaciones autoconvocadas. De igual forma, creemos que la población de mayor edad se concentraría en las organizaciones más institucionales y tradicionales del país, como juntas de vecinos por ejemplo, ya que se encuentran más familiarizados con estas vías de organización y en ciertos casos son las únicas a las que le otorgan “validez política”, en comparación a las demás formas de organización política.

Dicho esto, proponemos también una serie de preguntas piloto que nos permitirían corroborar esta hipótesis, esperando también una retroalimentación para pulir a fondo la conformación de esta investigación:
¿Qué organizaciones autoconvocadas conoció luego del estallido social? ¿En cuáles de ellas ha asistido o participado? ¿En una escala de 1 a 7, qué tan de acuerdo se encuentra usted con la organización autoconvocada? ¿Ha asistido a actividades de su junta de vecinos desde el estallido social? ¿Qué vías de organización política usted considera legítimas y válidas?

--
## Grupo 10

**Anakena Pavés, Diego Pérez, Paula Larenas y Paulina Gamboa**

El tema será las actitudes hacia l@s encapuchad@s, debido a que a raíz del estallido social ocurrido en Chile desde el 18 de Octubre, las manifestaciones en este país se hicieron masivas y cotidianas. Junto con esto se han incrementado los manifestantes que utilizan capuchas, lo que ha generado diversas percepciones de la población. Este estallido social, ha sido uno de los más grandes en la historia reciente de Chile, por lo que nos parece relevante comprender y conocer con más profundidad aspectos en relación con la percepción que tienen los habitantes chilenos a l@s encapuchad@s que han sido protagonistas de las movilizaciones. Nuestro objeto de estudio, serán las personas de 14 a 70 años habitantes de la región metropolitana, esto es debido a que l@s adolescentes han sido activos en las movilizaciones, incluso esta comenzó con los escolares evadiendo estaciones de metro, y hasta los 60 años porque queremos conocer también las actitudes de las personas mayores, que creemos son menos cercanas a l@s encapuchad@s. Seleccionamos la región metropolitana porque consideramos complicado acceder con la encuesta a más regiones. Nuestra hipótesis es que las actitudes de la ciudadanía frente a los/las encapuchados/as se muestran más positivas que como lo eran antes del estallido del 18 de Octubre. También tenemos otra idea de hipótesis, pero es algo que tenemos que conversar, esta es que las personas de mayor edad (50 años o más), muestran actitudes más negativas hacia las/los encapuchadas/os que las personas menores a 50 años.

## Grupo 11

**Juan Martinez Núñez & Matías Silva Araya**

En primera instancia se genera la idea de modificar la discusión planteada anteriormente, que correspondía a la temática de consumo de drogas en los jóvenes universitarios, clasificando tipos de drogas y perfil socioeconómico. La modificación se orienta más bien a caracterizar el perfil socioeconómico y sectorial de las personas que han participado en las manifestaciones de la reciente crisis social. La finalidad de esta caracterización es poder observar si existen afinidades entre ciertos perfiles socioeconómicos y la ubicación sectorial de los manifestantes. De la misma forma que buscamos encontrar si estos elementos son influyentes para determinar si las personas están a favor o en contra de las actuales movilizaciones, esto mediante la caracterización de su perfil socioeconómico, la ubicación sectorial, además de su apoyo a las manifestaciones. De esta manera se lograría saber cuáles son las características de las personas que están en contra de las últimas movilizaciones ciudadanas y las que están a favor, y con estas últimas además podremos extraer que tipo de movilizaciones son las que apoyan y las que están en desacuerdo.

# Prácticas del trabajo de investigación

- Las prácticas son actividades de trabajo grupal orientadas al desarrollo del trabajo de investigación central del curso, que es el desarrollo y análisis de un instrumento de medición en formato de cuestionario.

- Los grupos recibirán comentarios de ayudantes y profesor si entregan los informes de práctica en la fecha acordada (lunes siguiente a la sesión respectiva)

- Si no se ha cumplido con las fechas de entrega de las prácticas no se asegura la inclusión de las preguntas en el cuestionario final en formato web (ver detalles en sección evaluaciones)

- Sobre entregas: con el siguiente formato de archivo `prac1g10.pdf`, enviado vía Ucursos al profesor con copia al ayudante.


## Práctica 1: Operacionalización e indicadores {#prac1}

Esta práctica tiene como antecedente la adecuada definición de un problema de investigación. Para la viabilidad de la investigación es importante tener en cuenta que este problema será abordado mediante metodología de encuestas a población general.

En base al problema de investigación planteado por el grupo, realizar el proceso de operacionalización de las variables basado en la siguiente tabla de ejemplo:


| VARIABLE 	| Definición conceptual (constructo) 	| Definición real (dimensiones) 	| Definición operacional (indicadores) 	|
|-------------	|------------------------------------	|-------------------------------	|--------------------------------------	|
| (Variable_1)         	|                                    	|	|                                      	|
| (Variable_2)         	|                                    	|	|                                      	|
| (Variable_N)         	|                                    	|                               	|                                      	|
|          	|                                    	|                               	|                                      	|


<br>
<br>

## Práctica 2: Diseño de preguntas {#prac2}

- Establecer las posibles **categorías de respuesta** para cada indicador de la matriz de operacionalización

- Redactar preguntas para cada categoría de respuesta, según los contenidos y alternativas revisadas en la sesión respectiva


<br>
<br>

## Práctica 3: Diseño de cuestionario {#prac3}
